import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, existsSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { install } from '../src/codex-install.mjs';
const ok = (m) => console.log('  ok  ' + m);
const home = mkdtempSync(join(tmpdir(), 'shim-'));
const lines = [];
install({ home, out: (s) => lines.push(s) });
const shim = join(home, '.local', 'bin', 'enforcer');
assert.ok(existsSync(shim) && statSync(shim).mode & 0o100);
assert.ok(lines.some((l) => /export PATH=/.test(l)));
const r = spawnSync(shim, ['governor'], { encoding: 'utf8', env: { ...process.env, HOME: home, ENFORCER_HOME: home, GOVERNOR_HOME: join(home, 'g') } });
assert.match(r.stderr, /usage: enforcer/);
assert.match(r.stderr, /login/);
ok('shim resolves the stable runtime');
const s = spawnSync(process.execPath, [new URL('../bin/enforcer', import.meta.url).pathname, 'login', 'status'], { encoding: 'utf8', env: { ...process.env, HOME: home, ENFORCER_HOME: home } });
assert.equal(s.status === null, false);
ok('enforcer login status runs');
