#!/usr/bin/env node
// npm run gen:api — generate TypeScript types (openapi-typescript) and the
// openapi-fetch client index from the pinned specs in spec.lock.json.
// Output is committed: the plugin runs with no build step. test/api-gen.test.mjs
// calls generate() and fails when the committed files differ from it.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
export const SERVICES = ['graph', 'v3', 'files', 'governance'];

const header = (name, s) => `// GENERATED by lib/api/gen.mjs (npm run gen:api) from ${s.file} -- do not edit.\n// ${s.repo}@${s.ref} sha256:${s.sha256}\n`;

/** Every generated file as { relative name: content }, computed from the lock. */
export async function generate() {
  const lock = JSON.parse(readFileSync(resolve(here, 'spec.lock.json'), 'utf8'));
  const out = {};
  for (const n of SERVICES) {
    const s = lock.sources[n];
    const doc = JSON.parse(readFileSync(resolve(here, s.file), 'utf8'));
    const ast = await openapiTS(doc, { alphabetize: true });
    out[`${n}.d.ts`] = header(n, s) + astToString(ast);
  }
  const cap = (n) => n[0].toUpperCase() + n.slice(1);
  out['index.mjs'] = `// GENERATED by lib/api/gen.mjs (npm run gen:api) -- do not edit.
// One openapi-fetch client per service, typed by the matching .d.ts.
import createClient from 'openapi-fetch';

${SERVICES.map((n) => `/** @typedef {import('./${n}.d.ts').paths} ${cap(n)}Paths */`).join('\n')}

${SERVICES.map((n) => `/** @param {import('openapi-fetch').ClientOptions} [opts] @returns {import('openapi-fetch').Client<${cap(n)}Paths>} */
export const ${n}Client = (opts) => createClient(opts);`).join('\n\n')}
`;
  return out;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  for (const [f, body] of Object.entries(await generate())) writeFileSync(resolve(here, f), body);
  console.log('lib/api: generated types and clients');
}
