// GENERATED by lib/api/gen.mjs (npm run gen:api) -- do not edit.
// One openapi-fetch client per service, typed by the matching .d.ts.
import createClient from 'openapi-fetch';

/** @typedef {import('./graph.d.ts').paths} GraphPaths */
/** @typedef {import('./v3.d.ts').paths} V3Paths */
/** @typedef {import('./files.d.ts').paths} FilesPaths */
/** @typedef {import('./governance.d.ts').paths} GovernancePaths */

/** @param {import('openapi-fetch').ClientOptions} [opts] @returns {import('openapi-fetch').Client<GraphPaths>} */
export const graphClient = (opts) => createClient(opts);

/** @param {import('openapi-fetch').ClientOptions} [opts] @returns {import('openapi-fetch').Client<V3Paths>} */
export const v3Client = (opts) => createClient(opts);

/** @param {import('openapi-fetch').ClientOptions} [opts] @returns {import('openapi-fetch').Client<FilesPaths>} */
export const filesClient = (opts) => createClient(opts);

/** @param {import('openapi-fetch').ClientOptions} [opts] @returns {import('openapi-fetch').Client<GovernancePaths>} */
export const governanceClient = (opts) => createClient(opts);
